name: "Check Branch"

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch (main)
        if: github.base_ref == 'main' && github.head_ref != 'test'
        run: |
          echo "ERROR: You can only merge to main from test."
          exit 1
      - name: Check branch (test)
        if: github.base_ref == 'test' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge to test from dev."
          exit 1
